### ISSUE TITLE
module not building?

### ISSUE THREAD

**Issue by tkuebler** [Ryex/Dungeondraft-GoPackager#3]
checking out the project and running 'go build' doesn't work, new to go - what am I missing?  Wanting to build a mac version.

**Comment by Ryex** [comment]
Hi, The module is layed out as 
```
# tree
.
├── cmd
│   ├──  dungeondraft-pack
│   │     └── dungeondraft-pack.go
│   └── dungeondraft-unpack 
│          └── dungeondraft-unpack.go
├── internal
└── pkg
    ├── pack
    └── unpack 

```

This so so that the packages in `pkg/` can be reused in other projects. the commandline utilities are stored in `cmd/`

you can explicitly build the binaries by useing
```
$ go build /cmd/dungeondraft-pack
$ go build /cmd/dungeondraft-unpack
```
or you can use
```
go install ./...
```
to build and install them to your `$GOPATH/bin`

**Comment by tkuebler** [comment]
Thanks!!  Worked a charm.  Experienced dev, but haven't dealt with go modules yet, played with go early days.  :)

**Comment by ryexandra** [comment]
let me know how they work! there is windows specific logic to correct command line argument passing and path separators but those checks if the platform is windows. so it *should* work. but let me know if you have any problems.

**Comment by Ryex** [comment]
let me know how they work! there is windows specific logic to correct command line argument passing and path separators but those checks if the platform is windows. so it should work. but let me know if you have any problems.
