### ISSUE TITLE
Help for Go-noobs

### ISSUE THREAD

**Issue by kjgonzalez** [Ryex/Dungeondraft-GoPackager#5]
Hi, thank you for the wonderful package. just wanted to add some instructions for people on Linux who don't know the first thing about Go. I had to poke around a little bit, but this is what I found to work: 

1. if you've never installed go, run "sudo apt install golang", I used v1.18.1 at the time of this writing (and note, release of this repo was at v1.1.0)
2. download the source code, unpack at MAINPATH
3. `cd MAINPATH/cmd/dungeondraft-pack`
4. `go get github.com/sirupsen/logrus@v1.6.0` (if you skip this step and just type "go build", you'll get an error which tells you to do this anyway)
5. `go build` (this should build *pack)
6. `cd ../dungeondraft-unpack`
7. `go build` (this should build *unpack)
8. DONE!

**Comment by Ryex** [comment]
Alternatively as stated in the readme , provided you have go installed you can `go get`  the packer and unpacked directly.


```
go get github.com/ryex/dungeondraft-gopackager/cmd/dungeondraft-pack
go get github.com/ryex/dungeondraft-gopackager/cmd/dungeondraft-unpack
```

Which will build and install the binaries to `$GOBIN` with no need to seperately

**Comment by kjgonzalez** [comment]
ah, OK thank you! I honestly had no idea what that meant, I basically took the long way. thank you for the wonderful tool. helps me focus more on maps rather than getting assets ready.
